# Generated by Django 3.2.6 on 2021-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webpage_url', models.CharField(max_length=300)),
                ('webpage_title', models.CharField(max_length=500)),
                ('webpage_description', models.TextField(max_length=999)),
                ('webpage_keywords', models.TextField(max_length=700)),
            ],
        ),
    ]
