# Generated by Django 3.2.6 on 2021-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_contact_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('sitemap', models.CharField(max_length=100)),
            ],
        ),
    ]
