# Generated by Django 3.2.6 on 2021-10-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcontent',
            name='webpage_keywords',
            field=models.TextField(max_length=1000),
        ),
    ]
